---
- name: Ensure docker service is enabled
  service:
    name: 'docker'
    enabled: True

- name: Ensure TLS key basepath exists
  file:
    path: "{{ docker_tls_basepath }}"
    state: directory
  when: docker_tls_enable == True

- name: Copy TLS keys to docker host
  copy:
    content: '{{ item.content }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: '{{ item.mode }}'
  no_log: True
  with_items:
    - { content: '{{ docker_tls_keys.ca_cert|default("") }}', dest: '{{ docker_tls_basepath }}/ca.crt', mode: '0644' }
    - { content: '{{ docker_tls_keys.server_cert|default("") }}', dest: '{{ docker_tls_basepath }}/server.crt', mode: '0644' }
    - { content: '{{ docker_tls_keys.server_key|default("") }}', dest: '{{ docker_tls_basepath }}/server.key', mode: '0600' }
  when: docker_tls_enable == True and docker_tls_keys.ca_cert is defined
  notify:
    - Restart Docker

- name: Append TLS configuration to docker options
  set_fact:
    docker_opts: "{{ docker_opts }} -H tcp://{{ docker_tls_bind }}:{{ docker_tls_port }} --tlsverify --tlscacert={{ docker_tls_basepath }}/ca.crt --tlscert={{ docker_tls_basepath }}/server.crt --tlskey={{ docker_tls_basepath }}/server.key"
  when: docker_tls_enable == True

- name: Create Docker upstart default config file
  template:
    src: 'docker-defaults.j2'
    dest: '/etc/default/docker'
  when: ansible_service_mgr == "upstart"
  notify:
    - Restart Docker

- name: Create Docker sysvinit default config file
  template:
    src: 'docker-sysvinit-defaults.j2'
    dest: '/etc/default/docker'
  when: ansible_service_mgr == "sysvinit"
  notify:
    - Restart Docker

- name: Ensure docker systemd drop-in directory exists
  file:
    path: '/etc/systemd/system/docker.service.d'
    state: directory
  when: ansible_service_mgr == "systemd"

- name: Create Docker systemd drop-in file
  template:
    src: 'docker-systemd-service.j2'
    dest: '/etc/systemd/system/docker.service.d/override.conf'
  when: ansible_service_mgr == "systemd"
  register: dropinfile
  notify:
    - Restart Docker

- name: Reload systemd
  command: 'systemctl daemon-reload'
  when: ansible_service_mgr == "systemd" and dropinfile.changed
