---
- name: Update apt cache | Debian / Ubuntu
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Ensure APT transport HTTPS is installed | Debian / Ubuntu
  apt:
    name: 'apt-transport-https'
    state: installed

- name: Import Docker GPG key | Debian / Ubuntu
  apt_key:
    keyserver: 'p80.pool.sks-keyservers.net'
    id: '0EBFCD88'

- name: Enable Docker apt repository | Debian / Ubuntu
  apt_repository:
    repo: '{{ docker_apt_repo }}'
    state: present
  register: dockerrepo

- name: Update apt cache | Debian / Ubuntu
  apt:
    update_cache: yes
  when: dockerrepo.changed

- name: Ensure older Docker packages are removed (pre docker-CE)
  package:
    name: '{{ item }}'
    state: absent
  with_items:
    - docker-engine
    - docker
  register: dockercleaned

- name: Remove old systemd drop-in file
  file:
    path: '/etc/systemd/system/docker.service.d/override.conf'
    state: absent
  when: dockercleaned.changed

- name: Ensure Docker Community Edition is installed | Debian / Ubuntu
  apt:
    name: 'docker-ce'
    state: present
