---

- name: Reload systemd
  systemd:
    daemon_reload: true
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
  tags: skip_ansible_lint

- name: Restart Docker
  service: name=docker state=restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == 'docker')

- name: Start Docker
  service: name=docker state=started

- name: Reload Docker
  service: name=docker state=reloaded

- name: Stop Docker
  service: name=docker state=stopped
