---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
driver:
  name: docker
lint:
  name: yamllint
  enabled: False
  options:
    config-file: ../../../resources/.yamllint
platforms:
    - name: debian9
      image: geerlingguy/docker-debian9-ansible
      privileged: true
      command: /lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - debian
    # - name: centos6
    #   image: centos
    #   privileged: true
    #   command: /sbin/init
    #   ansible_groups:
    #     - redhat
    - name: centos7
      image: jgeusebroek/centos7-molecule
      privileged: true
      command: /usr/lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - redhat
    # - name: ubuntu1404
    #   image: jgeusebroek/ubuntu1404-molecule
    #   privileged: true
    #   command: /sbin/init
    #   groups:
    #     - ubuntu
    - name: ubuntu1604
      image: jgeusebroek/ubuntu1604-molecule
      privileged: true
      command: /lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - ubuntu
    - name: ubuntu1804
      image: jgeusebroek/ubuntu1804-molecule
      privileged: true
      command: /lib/systemd/systemd
      volumes:
        - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
      groups:
        - ubuntu
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
