---
- hosts: all

  tasks:
    - name: Install required packages (Debian / Ubuntu)
      apt:
        name: 'gnupg'
        update_cache: true
        state: present
      when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
