---
- hosts: all

  tasks:
    - name: Install required packages (Debian)
      apt:
        name: '{{ item }}'
        update_cache: yes
        state: present
      with_items:
        - gnupg
      when: ansible_distribution == 'Debian'
