---
- hosts: all

  tasks:
    - name: Install required packages (Debian)
      apt:
        name: 'gnupg'
        update_cache: yes
        state: present
      when: ansible_distribution == 'Debian'
